[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
charity_vault = "74GsU9xRv9qvVHXXvTAAmRp8ETTEAwGjV1UkJQ6BZNpG"

[programs.localnet]
charity_vault = "74GsU9xRv9qvVHXXvTAAmRp8ETTEAwGjV1UkJQ6BZNpG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/charity-vault/Cargo.toml"

[hooks]
